### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by mmjaeger** [bradpotter/genesis-page-templates#1]
getting a whole bunch of errors:
Notice: Use of undefined constant custom_loop - assumed 'custom_loop' in /Users/Marco/Sites/cms/wp-zementis/wp-content/plugins/genesis-page-templates/genesis-page-templates-functions.php on line 20
array(4) { ["templates/page-team.php"]=> string(19) "Page - Team members" ["page_archive.php"]=> string(7) "Archive" ["page_blog.php"]=> string(4) "Blog" ["custom_loop"]=> string(11) "Custom Loop" } 
Notice: Use of undefined constant custom_loop - assumed 'custom_loop' in /Users/Marco/Sites/cms/wp-zementis/wp-content/plugins/genesis-page-templates/genesis-page-templates-functions.php on line 20

**Comment by bradpotter** [comment]
What version of WordPress and Genesis are you using?
I made a minor change to genesis-page-templates-functions.php
Can you try again?

**Comment by mmjaeger** [comment]
The new version works - thanks for your help.
While I'm able to set the query args on the page now, how would you go about layout the entries - let's say I want to move the post info or show the entries in a grid?

**Comment by bradpotter** [comment]
I haven't worked on presentation options yet but I'm going to consider adding some.
